import { faker } from "@faker-js/faker";
import { Item } from "../types";

export const items: Item[] = [
  {
    id: faker.database.mongodbObjectId(),
    name: faker.commerce.productName(),
    image: faker.image.avatar(),
    store: 'eBay',
    price: faker.commerce.price({ min: 10, max: 2000, dec: 0 }),
    deliveryEstimationDate: faker.date.recent({ days: 30 }),
    received: false,
  },
  {
    id: faker.database.mongodbObjectId(),
    name: faker.commerce.productName(),
    image: faker.image.avatar(),
    store: 'Amazon',
    price: faker.commerce.price({ min: 10, max: 2000, dec: 0 }),
    deliveryEstimationDate: faker.date.recent({ days: 30 }),
    received: true,
  },
  {
    id: faker.database.mongodbObjectId(),
    name: faker.commerce.productName(),
    image: faker.image.avatar(),
    store: 'eBay',
    price: faker.commerce.price({ min: 10, max: 2000, dec: 0 }),
    deliveryEstimationDate: faker.date.recent({ days: 30 }),
    received: true,
  },
  {
    id: faker.database.mongodbObjectId(),
    name: faker.commerce.productName(),
    image: faker.image.avatar(),
    store: 'AliExpress',
    price: faker.commerce.price({ min: 10, max: 2000, dec: 0 }),
    deliveryEstimationDate: faker.date.recent({ days: 30 }),
    received: false,
  },
  {
    id: faker.database.mongodbObjectId(),
    name: faker.commerce.productName(),
    image: faker.image.avatar(),
    store: 'Amazon',
    price: faker.commerce.price({ min: 10, max: 2000, dec: 0 }),
    deliveryEstimationDate: faker.date.recent({ days: 30 }),
    received: true,
  },
  {
    id: faker.database.mongodbObjectId(),
    name: faker.commerce.productName(),
    image: faker.image.avatar(),
    store: 'eBay',
    price: faker.commerce.price({ min: 10, max: 2000, dec: 0 }),
    deliveryEstimationDate: faker.date.recent({ days: 30 }),
    received: false,
  },
  {
    id: faker.database.mongodbObjectId(),
    name: faker.commerce.productName(),
    image: faker.image.avatar(),
    store: 'AliExpress',
    price: faker.commerce.price({ min: 10, max: 2000, dec: 0 }),
    deliveryEstimationDate: faker.date.recent({ days: 30 }),
    received: false,
  },
  {
    id: faker.database.mongodbObjectId(),
    name: faker.commerce.productName(),
    image: faker.image.avatar(),
    store: 'AliExpress',
    price: faker.commerce.price({ min: 10, max: 2000, dec: 0 }),
    deliveryEstimationDate: faker.date.recent({ days: 30 }),
    received: true,
  },
  {
    id: faker.database.mongodbObjectId(),
    name: faker.commerce.productName(),
    image: faker.image.avatar(),
    store: 'eBay',
    price: faker.commerce.price({ min: 10, max: 2000, dec: 0 }),
    deliveryEstimationDate: faker.date.recent({ days: 30 }),
    received: true,
  },
]
